/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Case;
import Modele.GridBoard;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/**
 *
 * @author rifayath.david
 */
public class FenetrePrincipale extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form FenetrePrincipale
     */
    private final int height;
    private final int lenght;
    private GridBoard grille;
    private JButton gridButton[][];

    public FenetrePrincipale(int niveauPartie) {
        initComponents();
        grille = new GridBoard(niveauPartie);
        height = grille.getHeight();
        lenght = grille.getLenght();
        gridButton = new JButton[height][lenght];
        jPanel_Principal.setLayout(new GridBagLayout());
        jPanel_Principal.applyComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);

        for (int i = 0; i < height; i++) {
            for (int j = 0; j < lenght; j++) {
                final int x = i;
                final int y = j;
                gridButton[i][j] = new JButton();
                gridButton[i][j].setPreferredSize(new Dimension(25, 25));
                gridButton[i][j].setContentAreaFilled(false);
                gridButton[i][j].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                gridButton[i][j].setFocusPainted(false);
                gridButton[i][j].setMargin(new java.awt.Insets(2, 2, 2, 2));
                gridButton[i][j].setText(Integer.toString(grille.getGrille()[i][j].getValue()));
                gridButton[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (e.getModifiers() == MouseEvent.BUTTON3_MASK) {
                            rightClicCase(x, y);
                        } else if (e.getModifiers() == MouseEvent.BUTTON1_MASK) {
                            System.out.println("clic gauche");
                            leftClicCase(x, y);
                        }

                    }
                });
                GridBagConstraints gbc = new GridBagConstraints();                
                gbc.gridx = i;
                gbc.gridy = j;
                jPanel_Principal.add(gridButton[i][j], gbc);

            }
        }
        //grille.startChrono();
        grille.addObserver(this);
        //this.add();
    }

    private void leftClicCase(int x, int y) {

        if (gridButton[x][y].isEnabled()) {
            grille.updateValue(x, y);
        }
    }

    private void rightClicCase(int x, int y) {

        if (gridButton[x][y].isEnabled()) {
            grille.updateFlag(x, y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Haut = new javax.swing.JPanel();
        jLabel_chrono = new javax.swing.JLabel();
        jPanel_Principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Fichier = new javax.swing.JMenu();
        jMenuItem_scores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_chrono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/clock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_HautLayout = new javax.swing.GroupLayout(jPanel_Haut);
        jPanel_Haut.setLayout(jPanel_HautLayout);
        jPanel_HautLayout.setHorizontalGroup(
            jPanel_HautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HautLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel_chrono)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel_HautLayout.setVerticalGroup(
            jPanel_HautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HautLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_chrono)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel_chrono.getAccessibleContext().setAccessibleName("jLabel_chrono");

        javax.swing.GroupLayout jPanel_PrincipalLayout = new javax.swing.GroupLayout(jPanel_Principal);
        jPanel_Principal.setLayout(jPanel_PrincipalLayout);
        jPanel_PrincipalLayout.setHorizontalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel_PrincipalLayout.setVerticalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jMenu_Fichier.setText("Fichier");

        jMenuItem_scores.setText("Scores");
        jMenuItem_scores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_scoresActionPerformed(evt);
            }
        });
        jMenu_Fichier.add(jMenuItem_scores);

        jMenuBar1.add(jMenu_Fichier);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Haut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel_Haut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_scoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_scoresActionPerformed
        ScoreScreen scoreScreen = new ScoreScreen(this, true, grille);
        scoreScreen.setVisible(true);
    }//GEN-LAST:event_jMenuItem_scoresActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");
//        //java.util.Arrays.useLegacyMergeSort=true;
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FenetrePrincipale().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_chrono;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_scores;
    private javax.swing.JMenu jMenu_Fichier;
    private javax.swing.JPanel jPanel_Haut;
    private javax.swing.JPanel jPanel_Principal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        GridBoard tempGrid = (GridBoard) o;
        DateFormat formatter = new SimpleDateFormat("mm:ss");
        jLabel_chrono.setText(formatter.format(tempGrid.getTimeActuel()));
        if (tempGrid.getEtatPartie() == tempGrid.PARTIE_EN_COURS) {
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < lenght; j++) {
                    Case tempCase = tempGrid.getGrille()[i][j];
                    if (tempCase.getStatus() == Case.CASE_AFFICHER) {
                        gridButton[i][j].setText(" " + Integer.toString(tempCase.getValue()) + " ");
                        gridButton[i][j].setEnabled(false);
                        gridButton[i][j].setBorder(javax.swing.BorderFactory.createEtchedBorder());

                    } else if (tempCase.getStatus() == Case.CASE_INUTILE) {
                        gridButton[i][j].setEnabled(false);
                        gridButton[i][j].setBorder(javax.swing.BorderFactory.createEtchedBorder());
                    } else if (tempCase.getStatus() == Case.CASE_DRAPEAU) {
                        gridButton[i][j].setText("D");
                    } else if (tempCase.getStatus() == Case.CASE_INTERROGATIVE) {
                        gridButton[i][j].setText("?");
                    } else if (tempCase.getStatus() == Case.CASE_NOUVELLE) {
                        gridButton[i][j].setText(" 0 ");
                        gridButton[i][j].setEnabled(true);
                        gridButton[i][j].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    }
                }
            }
        } else {
            //L'utilisateur a perdu ou gagné
            afficherGrilleFinale(grille.getEtatPartie());
            Object[] options = new Object[2];
            options[0] = "Recommencer";
            options[1] = "Nouvelle Partie";

            int n = JOptionPane.showOptionDialog(this,
                    "Que voulez-vous faire ?",
                    "What next ... ?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //do not use a custom Icon
                    options, //the titles of buttons
                    options[0]); //default button title
            if (grille.getEtatPartie() == grille.PARTIE_GAGNE) {
                String name = JOptionPane.showInputDialog("Votre nom: ");
                grille.sauvegarder(name);
            }
            if (n == 0) {
                grille.initGrille();
            } else {
                this.dispose();
                MenuScreen.main(new String[2]);
                
            }
        }

        //gridLabel[tempCase.getX()][tempCase.getY()].setText(Integer.toString(tempCase.getValue()));
    }

    /**
     *
     * @param value si on a gagné, perdu
     */
    private void afficherGrilleFinale(int value) {
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < lenght; j++) {
                // afficher la grille finale en fonction de value
                if (grille.getGrille()[i][j].getStatus() == Case.CASE_DRAPEAU) {
                    //Drapeau mis à la case
                    if (grille.getGrille()[i][j].getBombe()) {
                        //Presence d'une bombe, donc bombe désamorcé
                        //Affiché bombe barré
                        gridButton[i][j].setText("X");
                    } else {
                        gridButton[i][j].setText("I");
                    }
                } else if (grille.getGrille()[i][j].getBombe()) {
                    gridButton[i][j].setText("B");
                }
                gridButton[i][j].setEnabled(false);
            }
        }
    }

    public GridBoard getGrille() {
        return grille;
    }
}
