/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.GridBoard;
import Modele.GridBoardReseau;
import javax.swing.JOptionPane;

/**
 *
 * @author rifayath.david
 */
public class MenuScreenReseau extends javax.swing.JDialog {

    private int niveauPartie;

    /**
     * Creates new form MenuScreen
     */
    public MenuScreenReseau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_NiveauF = new javax.swing.JRadioButton();
        jRadioButton_NiveauM = new javax.swing.JRadioButton();
        jRadioButton_NiveauD = new javax.swing.JRadioButton();
        jButton_lancerPartie = new javax.swing.JButton();
        jButton_quitter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton_Serveur = new javax.swing.JRadioButton();
        jRadioButton_Client = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/mine.png"))); // NOI18N
        jLabel1.setText("Démineur");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Niveau"));
        jPanel1.setToolTipText("Niveau");
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setName(""); // NOI18N

        buttonGroup1.add(jRadioButton_NiveauF);
        jRadioButton_NiveauF.setText("Facile");

        buttonGroup1.add(jRadioButton_NiveauM);
        jRadioButton_NiveauM.setText("Moyen");

        buttonGroup1.add(jRadioButton_NiveauD);
        jRadioButton_NiveauD.setText("Difficile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jRadioButton_NiveauF)
                .addGap(82, 82, 82)
                .addComponent(jRadioButton_NiveauM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jRadioButton_NiveauD)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_NiveauF)
                    .addComponent(jRadioButton_NiveauM)
                    .addComponent(jRadioButton_NiveauD))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jButton_lancerPartie.setText("Lancer la partie");
        jButton_lancerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lancerPartieActionPerformed(evt);
            }
        });

        jButton_quitter.setText("Quitter le mode");
        jButton_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quitterActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Joueur"));

        buttonGroup2.add(jRadioButton_Serveur);
        jRadioButton_Serveur.setText("Serveur");
        jRadioButton_Serveur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ServeurActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton_Client);
        jRadioButton_Client.setText("Client");
        jRadioButton_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_Serveur)
                .addGap(66, 66, 66)
                .addComponent(jRadioButton_Client)
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Serveur)
                    .addComponent(jRadioButton_Client))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton_lancerPartie)
                .addGap(64, 64, 64)
                .addComponent(jButton_quitter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_lancerPartie)
                    .addComponent(jButton_quitter))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_lancerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lancerPartieActionPerformed
        if (jRadioButton_NiveauF.isSelected()) {
            niveauPartie = 1;
        } else if (jRadioButton_NiveauM.isSelected()) {
            niveauPartie = 2;
        } else if (jRadioButton_NiveauD.isSelected()) {
            niveauPartie = 3;
        }
        if (niveauPartie == -1) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez choisir le niveau de la partie",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            new FenetreReseau(niveauPartie, GridBoardReseau.SERVEUR).setVisible(true);
        }


    }//GEN-LAST:event_jButton_lancerPartieActionPerformed

    private void jButton_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_quitterActionPerformed

    private void jRadioButton_ServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ServeurActionPerformed
        this.jPanel1.setEnabled(true);
        this.jRadioButton_NiveauD.setEnabled(true);
        this.jRadioButton_NiveauM.setEnabled(true);
        this.jRadioButton_NiveauF.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_ServeurActionPerformed

    private void jRadioButton_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ClientActionPerformed
        this.jPanel1.setEnabled(false);
        this.jRadioButton_NiveauD.setEnabled(false);
        this.jRadioButton_NiveauM.setEnabled(false);
        this.jRadioButton_NiveauF.setEnabled(false);
    }//GEN-LAST:event_jRadioButton_ClientActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton_lancerPartie;
    private javax.swing.JButton jButton_quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_Client;
    private javax.swing.JRadioButton jRadioButton_NiveauD;
    private javax.swing.JRadioButton jRadioButton_NiveauF;
    private javax.swing.JRadioButton jRadioButton_NiveauM;
    private javax.swing.JRadioButton jRadioButton_Serveur;
    // End of variables declaration//GEN-END:variables
}
