/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.GridBoard;
import Modele.Score;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;

/**
 *
 * @author rifayath.david
 */
public class ScoreScreen extends javax.swing.JFrame {

    /**
     * Creates new form ScoreScreen
     */
    JLabel[] playerName = new JLabel[10];
    JLabel[] playerScore = new JLabel[10];
    private GridLayout gLayout;
    private JTabbedPane onglets;
    JPanel[] ongletsPanel = new JPanel[3];
    JLabel[] titreOnglet = new JLabel[3];
    JPanel jPanel1;

    public ScoreScreen(java.awt.Frame parent, boolean modal, GridBoard grille) {
        initComponents();
        initializaComponents();
        //if (grille.getEtatPartie() == grille.PARTIE_GAGNE) {
//        String name = JOptionPane.showInputDialog("Votre nom: ");
//        grille.sauvegarder(name);
//        //}
//        playerName = new JLabel[10];
//        playerScore = new JLabel[10];
//        /*gLayout = new GridLayout(10, 3);
//         jPanel1.setLayout(gLayout);
//         jPanel1.applyComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);*/
        afficherScore(grille);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void afficherScore(GridBoard grille) {
        Map<String, List<Score>> allScore = grille.getAllScore();
        int i = 0;
        for (Map.Entry<String, List<Score>> entrySet : allScore.entrySet()) {
            String key = entrySet.getKey();
            List<Score> listNiveau = entrySet.getValue();
            for (Score score : listNiveau) {
                playerName[i] = new JLabel();
                playerScore[i] = new JLabel();
                playerName[i].setText(score.getName());
                //playerName[i].setHorizontalAlignment(SwingConstants.LEFT);
                DateFormat formatter = new SimpleDateFormat("mm:ss");
                playerScore[i].setText(String.valueOf(formatter.format(score.getScore())));

                ongletsPanel[score.getNiveau() - 1].add(playerName[i]);
                ongletsPanel[score.getNiveau() - 1].add(playerScore[i]);
                i++;
            }
        }

    }

    private void initializaComponents() {
        this.setLayout(new GridLayout());
        jPanel1 = new JPanel();
        onglets = new JTabbedPane();
        titreOnglet[0] = new JLabel("Score Facile");
        titreOnglet[1] = new JLabel("Score Moyen");
        titreOnglet[2] = new JLabel("Score Difficile");
        for (int i = 0; i < 3; i++) {
            ongletsPanel[i] = new JPanel(new GridLayout(0, 2));
            ongletsPanel[i].setPreferredSize(new Dimension(300, 50));
            onglets.addTab(titreOnglet[i].getText(), ongletsPanel[i]);
        }
        jPanel1.add(onglets);
        this.getContentPane().add(jPanel1);
    }
}
